title:        TechanJS
description:  "A visual, stock charting (Candlestick, OHLC, indicators) and technical analysis library built on D3."
url:          "http://techanjs.org"
author:       André Dumas

markdown:     kramdown
permalink:    pretty
exclude:      [Vagrantfile, README.md, src, CNAME, serve]
