title:        TechanJS
description:  "A visual, technical analysis and charting (Candlestick, OHLC, indicators) library built on D3."
url:          "http://techanjs.org"
author:       André Dumas

markdown:     kramdown
permalink:    pretty
exclude:      [Vagrantfile, README.md, src, CNAME]
